# Generated by Django 5.2.6 on 2025-09-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="mentor",
            field=models.ForeignKey(
                limit_choices_to={"role": "mentor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses_as_mentor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
